### PR TITLE
Standards linting

### PR DESCRIPTION
**Pull request by devinleonhart**
I've recently begun to use linters in my workflow to make sure I'm coding to industry standards. Other developers are not required to use the linters and I will maintain the standards over time. This pull request includes many changes to the master branch, one commit per file type. 

The linters are opinionated. So I've included config files for removing any opinions I don't agree with. Like enforcing trailing commas in javascript. While leaving in things I do agree with, like making sure "!important" is never included in CSS, even if it is valid.

@starim Please review.

### CODE REVIEW

**Comment by starim** [comment]
How do you run these lints?

**Comment by devinleonhart** [comment]
@starim

Linters are either used independently or in conjunction with an editor or task runner.

http://csslint.net/
http://jscs.info/
https://github.com/twbs/bootlint
https://github.com/brigade/scss-lint

For me, I use the atom package [linter](https://atom.io/packages/linter) and all of the [associated plugins](http://atomlinter.github.io/) for it that are relevant for the project. These show messages in my editor when I make a mistake. If you'd like to run them, you can check for equivalents in vim or run them independently. 

You also can ignore this and let me do it independently so it doesn't hassle you.

**Comment by starim** [comment]
We should add it to the Webpack test process if possible so it works automatically, for all developers.

**Comment by devinleonhart** [comment]
I would personally not like that. When jshint or otherwise was a part of `grunt watch` in other projects, it was more annoying than anything. I'd prefer to keep it in editor and manage things to my preference over time.

**Pull request merged**
