### PR TITLE
React tests

### PR DESCRIPTION
**Pull request by devinleonhart**
@starim 

Please review.

### CODE REVIEW

**Comment by starim** [comment]
Nice!

**Comment by starim** [comment]
I'm working on resolving merge conflicts with the Travis branch's code.

**Comment by starim** [comment]
So now that we have tests, should I switch Travis to run the test suite instead of trying to build the project?

**Comment by devinleonhart** [comment]
Yes, please. Since failing tests will report a bad build as well.

**Comment by starim** [comment]
Ready for merge.

**Comment by devinleonhart** [comment]
Once you finish and merge it in, the next thing I'd like you to do is begin
research into the implementation of Redux and scaffold that out. I'll teach
myself how to do some basic tests on the components that have already been
added.

**Pull request merged**
