### PR TITLE
Test catchup

### PR DESCRIPTION
**Pull request by devinleonhart**
@starim 

I would like to suggest we change our testing style to what is illustrated in the pull request.

It uses `import`, to keep our theme of using ES6.
It uses `import {createRenderer} from 'react-addons-test-utils';` to suppress the deprecation warning from using `require('react/addons').addons.TestUtils`
It uses the `Shallow Rendering` feature described at the bottom of https://facebook.github.io/react/docs/test-utils.html, making us not have to do DOM simulation.
It also uses [expect.js](https://github.com/Automattic/expect.js) , an assertion library I like more than [expect](https://github.com/mjackson/expect) (notice small difference in names)

What do you think?

### CODE REVIEW

**Comment by devinleonhart** [comment]
Here are the warnings I was getting  
```
Firefox 31.0.0 (Linux 0.0.0) ERROR: 'Warning: require('react/addons') is deprecated. Access using require('react-addons-{addon}') instead.'

ERROR: 'Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Footer`.'

ERROR: 'Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Footer`.'
```

**Comment by starim** [comment]
Yes, I'm glad you fixed the warnings. They bothered me too, but at the time I was preoccupied with just getting the test suite running and forgot about them.

**Comment by starim** [comment]
I think the new Footer test should be broken up into three different tests though. Like
```
it('uses the semantic HTML footer tag', () => {
  // test that the element is a footer
})

it('has a message declaring who created the game', () => {
  // test for footer message
})

it('has profile links for the authors', () => {
  // test that anchors link to our Github profiles
})
```

**Comment by devinleonhart** [comment]
@starim 
Please review.

**Pull request merged**
